default: Q1A Q1B Q2B

Q1A: Question1/q1a.cpp
	g++ -Wall Question1/q1a.cpp -o Q1A

Q1B: Question1/q1b.cpp
	g++ -Wall Question1/q1b.cpp -o Q1B

Q2B: Question2/q2b.cpp
	g++ -Wall Question2/q2b.cpp -o Q2B
