default: Q1 Q2 Q3 Q4 Q5

Q1: Question1/Complex.cpp Question1/template_array_search
	g++ -Wall Question1/template_array_search.cpp -o Q1

Q2: Question2/testStack.cpp
	g++ -o Q2 -Wall Question2/testStack.cpp

Q3: Question3/testing.cpp
	g++ -o Q3 -Wall Question3/testing.cpp

Q4: Question4/using_vectors.cpp
	g++ -o Q4 -Wall Question4/using_vectors.cpp

Q5: Question5/using_vector_ii.cpp
	g++ -o Q5 -Wall Question5/using_vector_ii.cpp