default: Q1a Q1b Q2b Q2c

Q1a: q1a.cpp
	g++ -Wall q1a.cpp -o Q1a

Q1b: q1b.cpp
	g++ -Wall q1b.cpp -o Q1b

Q2B: Q2b/q2b.cpp
	g++ -o Q2B -Wall Q2b/q2b.cpp 

Q2C: Q2c/q2c.cpp
	g++ -o Q2C -Wall Q2c/q2c.cpp
