default: Q1 Q2 Q3 Q4 Q5 Q6

Q1: Question1/list.cpp
	g++ -Wall Question1/list.cpp -o Q1

Q2: Question2/deques.cpp
	g++ -o Q2 -Wall Question2/deques.cpp

Q3: Question3/testWindGauge.cpp Question3/WindGauge.cpp
	g++ -o Q3 -Wall Question3/testWindGauge.cpp Question3/WindGauge.cpp

Q4: Question4/reverseVector.cpp
	g++ -o Q4 -Wall Question4/reverseVector.cpp

Q5: Question5/Lotto.cpp
	g++ -o Q5 -Wall Question5/Lotto.cpp

Q6: Question6/map.cpp
	g++ -o Q6 -Wall Question6/map.cpp

